# Simple docker compose file to run a mongo database
services:

  database:
    image: ${MONGO_IMAGE:-mongo:5.0.4}
    volumes:
      - /data/db/data/db:/data/db
    ports:
      - '27017:27017'
    env_file:
      - ./.env.${NODE_ENV}
    logging:
      driver: 'json-file'
      options:
        max-size: '100m'
        max-file: '1'
